"""add column user_id to labels

Revision ID: 038bf859fc2a
Revises: f30cb93e3e9d
Create Date: 2025-06-14 00:27:17.906518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '038bf859fc2a'
down_revision: Union[str, None] = 'f30cb93e3e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labels', sa.Column('user_id', sa.Integer(), nullable=False))

    op.create_foreign_key(
        'fk_labels_user_id_users',
        'labels', 'users',
        ['user_id'], ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_labels_user_id_users', 'labels', type_='foreignkey')
    op.drop_column('labels', 'user_id')
    # ### end Alembic commands ###
