"""add labels to notes table

Revision ID: f30cb93e3e9d
Revises: 8366053b1021
Create Date: 2025-06-13 20:45:45.724574

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f30cb93e3e9d"
down_revision: Union[str, None] = "8366053b1021"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notes", sa.Column("labels", sa.String()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notes", "labels")
    # ### end Alembic commands ###
